fragment PageParts on Page {
  __typename
  title
  hero {
    __typename
    badge
    title
    subtitle
    ctaPrimary
    ctaSecondary
    features {
      __typename
      text
    }
    images
    quote
  }
}
