fragment PageParts on Page {
  __typename
  ... on PageHome {
    title
    hero {
      __typename
      badge
      title
      subtitle
      ctaPrimary
      ctaSecondary
      quote
      features {
        __typename
        text
      }
      images
    }
    services {
      __typename
      badge
      title
      subtitle
      ctaText
      items {
        __typename
        id
        title
        description
        icon
      }
    }
    reviews {
      __typename
      badge
      title
      subtitle
      ctaText
      items {
        __typename
        author
        date
        rating
        text
        initial
      }
    }
    faq {
      __typename
      title
      subtitle
      ctaText
      items {
        __typename
        question
        answer
      }
    }
  }
  ... on PageAbout {
    title
    hero {
      __typename
      badge
      title
      description
      image
    }
    team {
      __typename
      badge
      title
      description1
      description2
      image
    }
    model {
      __typename
      badge
      title
      description1
      description2
      boxTitle
      features {
        __typename
        title
        description
        icon
      }
    }
    values {
      __typename
      title
      items {
        __typename
        title
        description
        icon
      }
    }
  }
  ... on PageServices {
    title
    hero {
      __typename
      badge
      title
      description
      image
    }
    immigration {
      __typename
      title
      subtitle
      items {
        __typename
        title
        description
      }
    }
    admin {
      __typename
      title
      subtitle
      items {
        __typename
        title
        description
      }
    }
  }
  ... on PageContact {
    title
    hero {
      __typename
      badge
      title
      description
      image
    }
    info {
      __typename
      location {
        __typename
        title
        line1
        line2
        note
      }
      phone {
        __typename
        title
        number
        email
        hours
      }
      social {
        __typename
        title
        description
        handle
        link
      }
    }
  }
}
